apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: 866934333672.dkr.ecr.ap-northeast-1.amazonaws.com/teamprojectrepo:app-1.1
          ports:
            - containerPort: 5000
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "mysql://test_user:test_user_password@mysql-db-service/taskdb"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Optionally, use "nlb" for Network LoadBalancer
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # Ensure the LB is public
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
